#image: registry.it.mcgill.ca/docker/rhel7-ansible
image: ruby:2.5
services:
    - redis:latest
    - postgres:latest

variables:
  # make sure that your .gitmodules file is configured to use relative paths!
  GIT_SUBMODULE_STRATEGY: recursive
  ANSIBLE_CONFIG: /builds/lts/murax/ansible.cfg

# Cache gems in between builds
cache:
  paths:
    - vendor/ruby

before_script:
  # Run the ssh-agent
  - eval $(ssh-agent -s)
  # Load the SSH key used for GitLab role deploys.
  #- ssh-add <(echo "$ROLE_DEPLOY_KEY")
  # Configure our Ansible playbooka
  - printenv
  - ruby -v
  - which ruby
  - gem install bundler
  - gem install capistrano
  - bundle install -j $(nproc) --path vendor  # Install dependencies into ./vendor/ruby

stages:
  - test
  - deploy_dev
  - deploy_qa
  - deploy_prod
  - cleanup

rspec:
  stage: test
  script:
    - bundle exec rspec
  tags:
    - azure

rubocop:
  tags:
    - azure
  stage: test
  script:
    - bundle exec rubocop
  tags:
    - azure

develop_deploy:
  tags:
    - azure
  stage: deploy_dev
  script:
    - cap development deploy
  only:
    - develop
  tags:
    - azure

staging_deploy:
  stage: deploy_qa
  script:
    - cap production deploy
  only:
    - master
  tags:
    - azure

production_deploy:
  stage: deploy_qa
  script:
    - cap production deploy
  only:
    - master
  when: manual
  tags:
    - azure

cleanup:
  stage: cleanup
  script:
    - rm -rf .vault-password
    - rm -rf /root/.ssh
  when: always
  tags:
    - azure
