#image: registry.it.mcgill.ca/docker/rhel7-ansible
image: ruby:2.3

variables:
  # make sure that your .gitmodules file is configured to use relative paths!
  GIT_SUBMODULE_STRATEGY: recursive
  ANSIBLE_CONFIG: /builds/lts/LIRAP//ansible.cfg


before_script:
  - ruby -v
  - which ruby

stages:
  - test
  - deploy_dev
  - deploy_qa
  - deploy_prod
  - cleanup

rspec:
  stage: deploy_dev
  script:
    - bundle exec rspec
  when: always

rubocop:
  script:
    - bundle exec rubocop
  when: always

deploy_app:
  stage: deploy_dev
  script:
    - gem install bundler --no-ri --no-rdoc
    - gem install capistrano
    - cap production deploy

cleanup:
  stage: cleanup
  script:
    - rm -rf .vault-password
    - rm -rf /root/.ssh
  when: always
