#image: registry.it.mcgill.ca/lts/murax/hyrax:latest
stages:
  - build
  - test
  - report
  - deploy

.base_minimal:
  image: alpine:latest
  cache: {}

.base:
  image: ruby:2.6.8
  cache:
    key: gems_and_packages
    paths:
      - apt-cache/
      - vendor/ruby
  before_script:
    - gem install bundler --no-document
    - bundle install --jobs $(nproc) "${FLAGS[@]}" --path=vendor

.base_db:
  extends: .base
  services:
    - postgres:latest
  variables:
    POSTGRES_DB: murax_gitlab
    POSTGRES_USER: murax
    POSTGRES_PASSWORD: ""
    RAILS_ENV: gitlab
  before_script:
    - export APT_CACHE_DIR=`pwd`/apt-cache && mkdir -pv $APT_CACHE_DIR
    - apt-get update -qq && apt-get -o dir::cache::archives="$APT_CACHE_DIR" install -yqq nodejs
    - gem install bundler --no-document
    - bundle install --jobs $(nproc) "${FLAGS[@]}" --path=vendor
    - bundle exec rake db:setup

build:rubocop:
  extends: .base
  stage: build
  script:
    - bundle exec rubocop
  tags:
    - azure

build:assets_precompile:
  extends: .base_db
  stage: build
  script:
    - bundle exec rake assets:precompile
  tags:
    - azure
