#image: registry.it.mcgill.ca/docker/rhel7-ansible
image: ruby:2.3
services:
    - redis:latest
    - postgres:latest

variables:
  # make sure that your .gitmodules file is configured to use relative paths!
  GIT_SUBMODULE_STRATEGY: recursive
  ANSIBLE_CONFIG: /builds/lts/LIRAP//ansible.cfg

# Cache gems in between builds
cache:
  paths:
    - vendor/ruby

before_script:
  - ruby -v
  - which ruby
  - bundle install -j $(nproc) --path vendor  # Install dependencies into ./vendor/ruby

stages:
  - test
  - deploy_dev
  - deploy_qa
  - deploy_prod
  - cleanup

rspec:
  script:
    - bundle exec rspec

rubocop:
  script:
    - bundle exec rubocop

deploy_app:
  stage: deploy_dev
  script:
    - gem install bundler --no-ri --no-rdoc
    - gem install capistrano
    - cap production deploy

cleanup:
  stage: cleanup
  script:
    - rm -rf .vault-password
    - rm -rf /root/.ssh
  when: always
