version: '3.3'

networks:
    appnetwork:
      driver: bridge
services:
  postgres:
    container_name: postgres
    build:
      context: ./docker/services/postgres
    image: db
    ports:
        - "5432:5432"
    networks:
      appnetwork:
        aliases:
            - postgres.docker.local

  adminer:
    container_name: adminer
    image: adminer
    restart: always
    ports:
      - 8090:8080
    depends_on:
      - postgres
    networks:
      appnetwork:
        aliases:
            - adminer.docker.local
  solr:
    container_name: solr
    image: solr:7.0
    ports:
      - 8983:8983
    networks:
      appnetwork:
        aliases:
            - solr.docker.local
  fcrepo:
    container_name: fcrepo
    build:
      context: ./docker/services/fcrepo
      args:
        FEDORA_VERSION: 4.7.5
        FEDORA_TAG: 4.7.5
        ModeshapeConfig: jdbc-postgresql
        JDBCConfig: -Dfcrepo.postgresql.username=fedora -Dfcrepo.postgresql.password=fedora123 -Dfcrepo.postgresql.host=postgres.docker.local -Dfcrepo.postgresql.port=5432 
    image: fcrepo
    ports:
      - 8888:8080
    depends_on:
      - postgres
    networks:
      appnetwork:
        aliases:
            - fcrepo.docker.local
  web:
    stdin_open: true
    build: .
    command:  bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - .:/usr/src/app
    depends_on:
      - postgres
      - fcrepo
      - solr
    ports:
      - "3000:3000"
      - "80:80"
      - "443:443"
    networks:
      appnetwork:
        aliases:
            - web.docker.local
