version: '3.3'

volumes:
  data:

networks:
    appnetwork:
      driver: bridge
services:
  postgres:
    container_name: postgres
    build:
      context: ./docker/services/postgres
    image: db
    ports:
        - "5432:5432"
    networks:
      appnetwork:
        aliases:
            - postgres.docker.local

  adminer:
    container_name: adminer
    image: adminer
    restart: always
    ports:
      - 8090:8080
    depends_on:
      - postgres
    networks:
      appnetwork:
        aliases:
            - adminer.docker.local
  solr:
    container_name: solr
    image: solr:7.0
    ports:
      - 8983:8983
    volumes:
      - ./solr/config/:/myconfig
    command: solr-create -c murax -d /myconfig
    networks:
      appnetwork:
        aliases:
            - solr.docker.local
  fcrepo:
    container_name: fcrepo
    build:
      context: ./docker/services/fcrepo
      args:
        FEDORA_VERSION: 4.7.5
        FEDORA_TAG: 4.7.5
        ModeshapeConfig: jdbc-postgresql
        JDBCConfig: -Dfcrepo.postgresql.username=fedora -Dfcrepo.postgresql.password=fedora123 -Dfcrepo.postgresql.host=postgres.docker.local -Dfcrepo.postgresql.port=5432 
    image: fcrepo
    ports:
      - 8888:8080
    depends_on:
      - postgres
    networks:
      appnetwork:
        aliases:
            - fcrepo.docker.local
  hyrax:
    container_name: hyrax
    stdin_open: true
    build: .
    volumes:
      - .:/storage/www/murax/current
      - data:/storage/www/murax/shared/bundle
    command: bash /docker/startup.sh
    depends_on:
      - postgres
      - fcrepo
      - solr
      - adminer
    env_file:
      - ./.env
    ports:
      - "3000:3000"
      - "80:80"
      - "443:443"
    networks:
      appnetwork:
        aliases:
            - hyrax.docker.local
