version: '3.4'

volumes:
  data:
  data-npm:
  db:
  solr_repo:
  solr_index:


networks:
    appnetwork:
      driver: bridge
services:
  mail:
    container_name: mailer
    image: bytemark/smtp
    restart: always
    environment:
      RELAY_HOST: mailhost.mcgill.ca
      RELAY_PORT: 25
    networks:
      appnetwork:
        aliases:
            - mail.docker.local
  postgres:
    container_name: postgres
    build:
      context: ./docker/services/postgres
    image: postgres:9.6-alpine
    environment:
      POSTGRES_PASSWORD: murax123
    ports:
        - "5432:5432"
    networks:
      appnetwork:
        aliases:
            - postgres.docker.local

  adminer:
    container_name: adminer
    image: adminer
    restart: always
    ports:
      - 8090:8080
    depends_on:
      - postgres
    networks:
      appnetwork:
        aliases:
            - adminer.docker.local
  solr:
    container_name: solr
    image: solr:7.2
    ports:
      - "8982:8983"
    volumes:
      - data:/var/solr
      - ./solr:/opt/solr/server/solr/configsets/myconfig
    command:
      - solr-precreate
      - murax
      - /opt/solr/server/solr/configsets/myconfig
    networks:
      appnetwork:
        aliases:
            - solr.docker.local
  fcrepo:
    container_name: fcrepo
    build:
      context: ./docker/services/fcrepo
      args:
        FEDORA_VERSION: 4.7.5
        FEDORA_TAG: 4.7.5
        ModeshapeConfig: jdbc-postgresql
        JDBCConfig: -Dfcrepo.postgresql.username=fedora -Dfcrepo.postgresql.password=fedora123 -Dfcrepo.postgresql.host=postgres.docker.local -Dfcrepo.postgresql.port=5432
    image: fcrepo
    ports:
      - "8888:8080"
    depends_on:
      - postgres
    networks:
      appnetwork:
        aliases:
            - fcrepo.docker.local
  murax:
    image: registry.it.mcgill.ca/lts/murax/hyrax:latest
    container_name: murax
    stdin_open: true
    volumes:
      - .:/storage/www/murax/current
      - data:/storage/www/murax/shared/bundle
      - data-npm:/storage/www/murax/node_modules
    command: bash /docker/startup.sh
    depends_on:
      - postgres
      - fcrepo
      - solr
      - adminer
    env_file:
      - ./.env
    ports:
      - "3000:3000"
      - "80:80"
      - "443:443"
    networks:
      appnetwork:
        aliases:
            - murax.docker.local
