terms:
  - id: http://bibliographic-ontology.org/bibo/bibo.php#Article
    term: Article
  - id: http://bibliographic-ontology.org/bibo/bibo.php#Book
    term: Book
  - id: http://bibliographic-ontology.org/bibo/bibo.php#Thesis
    term: Thesis
  - id: http://bibliographic-ontology.org/bibo/bibo.php#Chapter
    term: Chapter
  - id: http://bibliographic-ontology.org/bibo/bibo.php#Report
    term: Report
  - id: https://duraspace.org/archive/vivo/vivo.owl#ConferencePaper
    term: Conference Paper
  - id: https://duraspace.org/archive/vivo/vivo.owl#ConferencePoster
    term: Conference Poster
  - id: http://data.semanticweb.org/ns/swc/ontology#Paper
    term: Paper
  - id: https://duraspace.org/archive/vivo/vivo.owl#Presentation
    term: Presentation
