terms:
  - id: Article
    term: Article
  - id: Book
    term: Book
  - id: Thesis
    term: Thesis
  - id: Chapter
    term: Chapter
  - id: Report
    term: Report
  - id: Conference Paper
    term: Conference Paper
  - id: Conference Poster
    term: Conference Poster
  - id: Paper
    term: Paper
  - id: Presentation
    term: Presentation
