#
# To integrate your app with Google Analytics, uncomment the lines below and add your API key information.
#
 analytics:
   app_name: escholarship
   app_version: 1.0
   privkey_path: /storage/www/murax/current/escholarship-4189a4c11f03.p12
   privkey_secret: 4189a4c11f036ed13486b009b2695bab0d11216a
   client_email: escholarship@escholarship.iam.gserviceaccount.com
