development:
  adapter: solr
  url: <%= ENV['SOLR_URL'] %>/<%= ENV['SOLR_CORE'] %>_dev
test: &test
  adapter: solr
  url: <%= ENV['SOLR_URL'] %>/<%= ENV['SOLR_CORE'] %>_test
staging:
  adapter: solr
  url: <%= ENV['SOLR_URL'] %>/<%= ENV['SOLR_CORE'] %>_qa
production:
  adapter: solr
  url: <%= ENV['SOLR_URL'] %>/<%= ENV['SOLR_CORE'] %>_prod
