development:
  adapter: redis
  url: redis://localhost:6379/1
  channel_prefix: murax_development

test:
  adapter: redis
  url: redis://localhost:6379/1
  channel_prefix: murax_test

production:
  adapter: redis
  url: redis://localhost:6379/1
  channel_prefix: murax_production
