
default: &default
    adapter: postgresql #postgis
    encoding: unicode
    database: <%= ENV['POSTGRES_DBNAME'] %>
    # For details on connection pooling, see rails configuration guide
    # http://guides.rubyonrails.org/configuring.html#database-pooling
    pool: 10
    host: <%= ENV['POSTGRES_HOST'] || ENV['DB_ENV_POSTGRES_HOST'] %>
    username: <%= ENV['POSTGRES_USER'] || ENV['DB_ENV_POSTGRES_USER'] %>
    password: <%= ENV['POSTGRES_PASSWORD'] || ENV['DB_ENV_POSTGRES_PASSWORD'] %>

development:
    <<: *default

test:
    <<: *default
    database: test_samvera

production:
    <<: *default
    pool: 20

staging:
    <<: *default
    pool: 10
