default: &default
  user: <%= ENV['FCREPO_USER'] %>
  password: <%= ENV['FCREPO_PASSWORD'] %>
  url: http://<%= ENV['FCREPO_HOST'] %>:<%= ENV['FCREPO_PORT'] || 8983 %>/rest
  base_path: /<%= ENV['FCREPO_BASE_PATH'] || fcrepo %>:

development:
  <<: *default
  base_path: /<%= ENV['FCREPO_BASE_PATH'] || fcrepo_dev %>:

test:
  <<: *default
  base_path: /<%= ENV['FCREPO_BASE_PATH'] ||  fcrepo_test %>:

production:
  <<: *default
  base_path: /<%= ENV['FCREPO_BASE_PATH'] || fcrepo_prod %>:
