default: &default
  user: <%= ENV['FCREPO_ADMIN_USER'] %>
  password: <%= ENV['FCREPO_ADMIN_PASSWORD'] %>

development:
  <<: *default
  url: http://<%= ENV['FCREPO_DEVELOPMENT_HOST']  %>:<%= ENV['FCREPO_DEVELOPMENT_PORT'] || 8080 %>/<%= ENV['FCREPO_DEVELOPMENT_BASE_PATH'] || 'fcrepo' %>/rest
  base_path: /samvera

test:
  <<: *default
  url: http://<%= ENV['FCREPO_TEST_HOST'] %>:<%= ENV['FCREPO_TEST_PORT'] || 8080 %>/<%= ENV['FCREPO_TEST_BASE_PATH'] || 'fcrepo' %>/rest
  base_path: /test

staging:
  <<: *default
  url: http://<%= ENV['FCREPO_STAGING_HOST'] %>:<%= ENV['FCREPO_STAGING_PORT'] || 8080 %>/<%= ENV['FCREPO_STAGING_BASE_PATH'] || 'fcrepo' %>/rest
  base_path: /staging

production:
  <<: *default
  url: http://<%= ENV['FCREPO_PROD_HOST'] %>:<%= ENV['FCREPO_PROD_PORT'] || 8080 %>/<%= ENV['FCREPO_PROD_BASE_PATH'] || 'fcrepo' %>/rest
  base_path: /production
