default: &default
  user: <%= ENV['FEDORA_USER'] %>
  password: <%= ENV['FEDORA_PASSWORD'] %>
  url: <%= ENV['FEDORA_URL']  %>

development:
  user: <%= ENV['FEDORA_USER'] %>
  password: <%= ENV['FEDORA_PASSWORD'] %>
  url: <%= ENV['FEDORA_URL']  %>
  base_path: /<%= ENV['FEDORA_BASE_PATH'] %>

test:
  user: <%= ENV['FEDORA_USER'] %>
  password: <%= ENV['FEDORA_PASSWORD'] %>
  url: <%= ENV['FEDORA_URL']  %>
  base_path: /<%= ENV['FEDORA_BASE_PATH'] %>_test

staging:
  user: <%= ENV['FEDORA_USER'] %>
  password: <%= ENV['FEDORA_PASSWORD'] %>
  url: <%= ENV['FEDORA_URL']  %>
  base_path: /<%= ENV['FEDORA_BASE_PATH'] %>

production:
  user: <%= ENV['FEDORA_USER'] %>
  password: <%= ENV['FEDORA_PASSWORD'] %>
  url: <%= ENV['FEDORA_URL']  %>
  base_path: /<%= ENV['FEDORA_BASE_PATH'] %>
