default: &default
  user: <%= ENV['FEDORA_USER'] %>
  password: <%= ENV['FEDORA_PASSWORD'] %>
  url: <%= ENV['FEDORA_URL']  %>

development:
  <<: *default
  base_path: /samvera

test:
  <<: *default
  base_path: /test

staging:
  <<: *default
  base_path: /staging

production:
  <<: *default
  base_path: /production
