# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

default: &default
  admin_name: <%= ENV["ADMIN_NAME"] %>
  admin_email: <%= ENV["ADMIN_EMAIL"] %>
  admin_username: <%= ENV["ADMIN_USERNAME"] %>
  admin_password: <%= ENV["ADMIN_PASSWORD"] %>
  domain_name: <%= ENV["VIRTUAL_HOST"] %>
  secret_key_base: <%= ENV["SECRET_TOKEN"] %>
development:
  <<: *default
  secret_key_base: <%= ENV["SECRET_TOKEN"] %>

test:
  <<: *default
  secret_key_base: 8dde48de923ea5f3ff8a447026fc178c02229fe2214a826fc7087039413e513d0d2073dd53cbdcf8f813e176df836866b8310efe0b11374ba852ba1e460aa6d6

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  <<: *default
  secret_key_base: <%= ENV["SECRET_TOKEN"] %>
