# This is a sample config file that points to a solr server for each environment
development:
  url: http://<% ENV['SOLR_DEVELOPMENT_HOST'] %>:<%= ENV['SOLR_DEVELOPMENT_PORT'] || 8983 %>/solr/samvera
test:
  url: http://<% ENV['SOLR_TEST_HOST'] %>:<%= ENV['SOLR_TEST_PORT'] || 8983 %>/solr/samvera
production:
  url: http://<% ENV['SOLR_PROD_HOST'] %>:<%= ENV['SOLR_PROD_PORT'] || 8983 %>/solr/samvera
